default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREAD") { 5 } %>
  timeout: 5000
  username: postgres
  password: chunu@2006
  host: localhost

development:
  <<: *default
  database: development_instagram

test:
  <<: *default
  database: test_instagram

production:
  <<: *default
  database: production_instagram
